### PR TITLE
More consistent exception handling. Default end_timestamp for getRTFA.

### LINKED ISSUE #33: Handle BigDecimal exceptions for invalid inputs
## Issue

We represent monetary amounts as strings in our proto and then convert these strings to `BigDecimal` to process in Java. In the case that an invalid string is given as input in [the constructor](https://docs.oracle.com/javase/8/docs/api/java/math/BigDecimal.html#BigDecimal-java.lang.String-), a `NumberFormatException` is thrown. We handle this for `createAccount` by catching the exception in `FinAppService`. This problem will apply to future PRs that require an amount as input. 

We should figure out a better way to handle this exception and provide useful output to users.

## Next steps

1. Consider different solutions for handling this exception, including possibly adding it to signatures
2. Change current methods that use this `BigDecimal` constructor (`createAccount`, `moveAccountBalance`, and more)
3. Ensure that future methods that will run into this problem will handle the exception similarly

### PR DESCRIPTION
**Pull request by voulg**
Fixes #33, #46 (and partially #34)

I also noticed we do not have very good coverage for the exceptions we throw, I plan to do this with a separate PR.

### CODE REVIEW

File: server/src/main/java/com/google/finapp/FinAppService.java [hunk 1]
```diff
@@ -58,28 +59,38 @@ public void createCustomer(
     responseObserver.onCompleted();
   }
 
+  private BigDecimal getNonNegativeBigDecimal(String value) throws StatusException {
```
Comment (haseebajmal) [inline server/src/main/java/com/google/finapp/FinAppService.java:62]: nit: I'd suggest moving this private method towards the end of the file so that it's consistent with the current ordering of the members.

File: server/src/main/java/com/google/finapp/FinAppService.java [hunk 2]
```diff
@@ -191,10 +176,21 @@ public void getRecentTransactionsForAccount(
     ByteArray accountId = ByteArray.copyFrom(request.getAccountId().toByteArray());
     Timestamp beginTimestamp = Timestamp.fromProto(request.getBeginTimestamp());
     Timestamp endTimestamp = Timestamp.fromProto(request.getEndTimestamp());
+    if (endTimestamp.equals(Timestamp.MIN_VALUE)) {
```
Comment (haseebajmal) [inline server/src/main/java/com/google/finapp/FinAppService.java:179]: nit: Can we instead do something like:
`Timestamp endTimestamp = request.hasEndTimestamp() ? Timestamp.fromProto(request.getEndTimestamp()) : Timestamp.MAX_VALUE`

It's not immediately obvious to me that Timestamp.fromProto(request.getEndTimestamp()) would result in MIN_VALUE when the field is empty.

**Review by haseebajmal — APPROVED** [review]

File: server/src/main/java/com/google/finapp/FinAppService.java [hunk 3]
```diff
@@ -58,28 +59,38 @@ public void createCustomer(
     responseObserver.onCompleted();
   }
 
+  private BigDecimal getNonNegativeBigDecimal(String value) throws StatusException {
+    BigDecimal value_decimal = null;
```
[the remark this answers is not in the document]
Comment (voulg) [reply server/src/main/java/com/google/finapp/FinAppService.java]: Done

File: server/src/main/java/com/google/finapp/FinAppService.java (hunk 2 above)
Comment (voulg) [reply server/src/main/java/com/google/finapp/FinAppService.java:161]: This is a good point. However, I was thinking in proto3 that does not have optional fields and the hasFieldX() API. Given that we're moving to proto3 API we'd eventually need to write this in this way.

File: server/src/main/java/com/google/finapp/FinAppService.java (hunk 1 above)
Comment (voulg) [reply server/src/main/java/com/google/finapp/FinAppService.java]: done

File: server/src/main/java/com/google/finapp/SpannerDaoImpl.java [hunk 4]
```diff
@@ -114,13 +110,8 @@ public void createCustomerRole(
   @Override
   public ImmutableMap<ByteArray, BigDecimal> moveAccountBalance(
       ByteArray fromAccountId, ByteArray toAccountId, BigDecimal amount)
```
Comment (c24t) [inline server/src/main/java/com/google/finapp/SpannerDaoImpl.java:112]: I see you catch negative `amount` in the caller now, but this is still a public method. Should negative `amount`s be legal here?

File: server/src/main/java/com/google/finapp/SpannerDaoImpl.java [hunk 5]
```diff
@@ -155,22 +148,19 @@ public void createCustomerRole(
...
   }
 
   @Override
   public BigDecimal createTransactionForAccount(
-      ByteArray accountId, BigDecimal amount, boolean isCredit) throws SpannerDaoException {
-    if (amount.signum() == -1) {
-      throw new IllegalArgumentException(
-          String.format("Amount transferred cannot be negative. amount: %s", amount.toString()));
-    }
+      ByteArray accountId, BigDecimal amount, boolean isCredit)
```
Comment (c24t) [inline server/src/main/java/com/google/finapp/SpannerDaoImpl.java:162]: Same question about `amount` as above.

**Review by c24t — APPROVED** [review]
LGTM, only minor comments.

File: server/src/main/java/com/google/finapp/SpannerDaoImpl.java [hunk 6]
```diff
@@ -225,20 +220,13 @@ public BigDecimal createTransactionForAccount(
...
-          String.format("Invalid timestamp range. %s is before %s.", endTimestamp, beginTimestamp));
-    }
     Statement statement =
         Statement.newBuilder(
                 "SELECT * "
                     + "FROM TransactionHistory "
                     + "WHERE AccountId = @accountId AND "
-                    + "EventTimestamp BETWEEN @beginTimestamp AND @endTimestamp "
+                    + "EventTimestamp >= @beginTimestamp AND "
+                    + "EventTimestamp < @endTimestamp "
```
[the remark this answers is not in the document]
Comment (voulg) [reply server/src/main/java/com/google/finapp/SpannerDaoImpl.java:229]: Correct, this will become important in the pagination PR coming soon.

File: server/src/main/java/com/google/finapp/SpannerDaoImpl.java [hunk 7]
```diff
@@ -199,10 +192,12 @@ public BigDecimal createTransactionForAccount(
...
 
                     if (newBalance.signum() == -1) {
-                      throw new IllegalArgumentException(
-                          String.format(
-                              "Account balance cannot be negative. original account balance: %s, amount to be removed: %s",
-                              oldBalance.toString(), amount.toString()));
+                      throw Status.INVALID_ARGUMENT
+                          .withDescription(
+                              String.format(
+                                  "Account balance cannot be negative. original account balance: %s, amount to be removed: %s",
```
[the remark this answers is not in the document]
Comment (voulg) [reply server/src/main/java/com/google/finapp/SpannerDaoImpl.java:198]: Thanks I'll fix it in a follow-up PR

File: server/src/main/java/com/google/finapp/SpannerDaoImpl.java (hunk 4 above)
Comment (voulg) [reply server/src/main/java/com/google/finapp/SpannerDaoImpl.java:112]: This is a non-public class, so it is ok-ish to assume things about its input. This is also documented in the interface were we mention that the amount is expected to be non-negative. I do see the concern, but I think in this case it's an internal implementation class and there's documentation in the interface so it's probably ok.

File: server/src/main/java/com/google/finapp/SpannerDaoImpl.java (hunk 5 above)
Comment (voulg) [reply server/src/main/java/com/google/finapp/SpannerDaoImpl.java:162]: Resolving this and we can continue the conversation above.
